[package]
name = "simulator"
description = "Simulator for an LC-3 Virtual Machine, written in Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
num-derive = "0.4.2"
byteorder = "1.5.0"
clap = { version = "4.5.31", features = ["derive"] }
termios = "0.3.3"
